version: '3.8'

services:
  front:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_URL: http://back:3002
    ports:
      - 3000:80
    depends_on:
      - back
  back:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 4500:3002
    env_file:
      - .env
